---
provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  piedpiper-validator-function:
    lang: python3-flask
    handler: ./piedpiper-validator-function
    image: piedpiper-validator-function:latest
    secrets:
      - storage-access-key
      - storage-secret-key
  piedpiper-validator-gateway:
    lang: python3-flask
    handler: ./piedpiper-validator-gateway
    image: piedpiper-validator-gateway:latest
    secrets:
      - storage-access-key
      - storage-secret-key
